# See the file LICENSE.txt in this directory for license information for the
# Caja Corkboard demo.

# Google App Engine application configuration file.
#
# @author kpreid@switchb.org

application: caja-corkboard
version: 1
runtime: python
api_version: 1

handlers:
- url: /r
  static_dir: static

- url: /.*
  script: corkboard.py